// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBAStatsAPI.Infra;

#nullable disable

namespace NBAStatsAPI.Infra.Migrations
{
    [DbContext(typeof(NBAStatsAPIContext))]
    [Migration("20230106033224_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NBAStatsAPI.Dominio.Model.Jogador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("APG")
                        .HasColumnType("decimal(3,1)");

                    b.Property<long>("AssistenciasTotais")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BPG")
                        .HasColumnType("decimal(3,1)");

                    b.Property<long>("BlocksTotais")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<decimal>("PPG")
                        .HasColumnType("decimal(3,1)");

                    b.Property<long>("PontosTotais")
                        .HasColumnType("bigint");

                    b.Property<long>("PosicaoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("RPG")
                        .HasColumnType("decimal(3,1)");

                    b.Property<long>("RebotesTotais")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SPG")
                        .HasColumnType("decimal(3,1)");

                    b.Property<long>("StealsTotais")
                        .HasColumnType("bigint");

                    b.Property<long>("TimeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PosicaoId");

                    b.HasIndex("TimeId");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("NBAStatsAPI.Dominio.Model.Posicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Abreviacao")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Posicoes");
                });

            modelBuilder.Entity("NBAStatsAPI.Dominio.Model.Time", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("NBAStatsAPI.Dominio.Model.Jogador", b =>
                {
                    b.HasOne("NBAStatsAPI.Dominio.Model.Posicao", "Posicao")
                        .WithMany("Jogadores")
                        .HasForeignKey("PosicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NBAStatsAPI.Dominio.Model.Time", "Time")
                        .WithMany("Jogadores")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posicao");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("NBAStatsAPI.Dominio.Model.Posicao", b =>
                {
                    b.Navigation("Jogadores");
                });

            modelBuilder.Entity("NBAStatsAPI.Dominio.Model.Time", b =>
                {
                    b.Navigation("Jogadores");
                });
#pragma warning restore 612, 618
        }
    }
}
